baatcheet/baatcheet/urls.py
from django.contrib import admin
from django.urls import path,include
from chat_app import urls

app_name='chat_app'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(urls)),
]

baatcheet/chat_app/urls.py
from django.urls import path
from . import views

app_name='chat_app'
urlpatterns=[
    path("",views.home,name='home'),
    path("room/<str:id>/",views.room,name='room'),
    path("create-room/",views.createRoom,name='createRoom'),
    path("delete-room/<str:id>/",views.deleteRoom,name='deleteRoom'),
    path("update-room/<str:id>/",views.updateRoom,name='updateRoom'),
    path("logoutUser",views.logoutUser,name='logoutUser'),
    path("login_register",views.login_register,name='login_register'),
    path("registerUser",views.registerUser,name='registerUser'),
    path("deleteMessage/<str:id>/",views.deleteMessage,name='deleteMessage'),
    path("editMessage/<str:id>/",views.editMessage,name='editMessage'),
]

baatcheet/chat_app/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User


class Topic(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name
# Create your models here.
class Room(models.Model):
    host=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    participants=models.ManyToManyField(User,related_name='participants')
    name=models.CharField(max_length=200)
    discription=models.TextField(null=True,blank=True)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-updated','-created']

    def __str__(self) -> str:
        return self.name
    

class Message(models.Model):
    room=models.ForeignKey(Room,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    body=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.body[:50]
    
class RoomForm(ModelForm):
    class Meta:
        model=Room
        fields= '__all__'

baatcheet/chat_app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
from .models import Room,RoomForm,Topic,Message
from django.db.models import Q
from django.contrib.auth.decorators import login_required
# Create your views here.
def logoutUser(request):
    logout(request)
    return redirect('chat_app:home')

def registerUser(request):
    form=UserCreationForm()
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.username=user.username.lower()
            user.save()
            return redirect('chat_app:login_register')
    context={'switch':'register','form':form}
    return render(request,'chat_app/login_register.html',context)


def login_register(request):
    context={'switch':'login'}
    if request.user.is_authenticated:
        return redirect('chat_app:home')

    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('chat_app:home')
        else :
            messages.error(request,"User is invalid")
            return redirect('chat_app:login_register')
    return render(request,'chat_app/login_register.html',context)

        

def home(request):
    q=request.GET.get('search') if request.GET.get('search') !=None else ''
    room=Room.objects.filter(Q(topic__name__icontains=q)| Q(discription__icontains=q) | Q(name__icontains=q))
    topics=Topic.objects.all()
    context={'rooms':room, 'topics':topics}
    return render(request,'chat_app/home.html',context)

def deleteMessage(request,id):
    message=Message.objects.get(id=id)
    if request.user==message.user:
        message.delete()
    else :
        messages.error(request,"You are not allowed to delete")
    return redirect('chat_app:room',id=message.room.id)

def editMessage(request,id):
    message=Message.objects.get(id=id)
    message.delete()
    return redirect('chat_app:room',id=message.room.id)


def room(request,id):
    room=Room.objects.get(id=id)
    participants=room.participants.all()
    if request.method=='POST':
        Message.objects.create(
            room=Room.objects.get(id=id),
            user=request.user,
            body=request.POST.get('addComment')
        )
        room.participants.add(request.user)
        return redirect('chat_app:room',id=room.id)
    roomMessages=room.message_set.all().order_by('-created')
    context={'rooms':room,'roomMessages':roomMessages,'participants':participants}
    return render(request,'chat_app/room.html',context)

@login_required(login_url='chat_app:login_register')
def createRoom(request):
    form=RoomForm(request.POST)
    if request.method=='POST':
        form=RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('chat_app:home'))
        else:
            form=RoomForm(request.POST)
    context={'form':form}
    return render(request,'chat_app/createroom.html',context)

@login_required(login_url='chat_app:login_register')
def deleteRoom(request,id):
    room=Room.objects.get(id=id)
    if request.method=='POST':
        room=Room.objects.get(id=id)
        room.delete()
        return redirect('chat_app:home')
    return render(request,'chat_app/delete.html',{'rooms':room})

@login_required(login_url='chat_app:login_register')
def updateRoom(request,id):
    room=Room.objects.get(id=id)
    form=RoomForm(instance=room)
    if request.method=='POST':
        if request.user!=room.host:
            return HttpResponse("<h1>You are not allowed to edit this room</h1>")
        form=RoomForm(request.POST,instance=room)
        if form.is_valid():
            form.save()
            return redirect('chat_app:home')
    return render(request,'chat_app/updateRoom.html',{'form':form})

baatcheet/chat_app/templates/chat_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Baatcheet</h1>
    {% block content %}
    {% endblock %}
</body>
</html>

baatcheet/chat_app/templates/chat_app/createroom.html
{% extends 'chat_app/base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="submit">
    </form>
    {% endblock %}

baatcheet/chat_app/templates/chat_app/delete.html
{% extends 'chat_app/base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Do you want to delete {{rooms.name}}??</p>
        <a href="{% url 'chat_app:home' %}">Go back</a>
       <input type="submit" value="Confirm">

    </form>
    {% endblock %}

baatcheet/chat_app/templates/chat_app/home.html
{% extends 'chat_app/base.html' %}
{% block content %}

<style>
    .parent{
        display: grid;
        grid-template-columns: 1fr 3fr;
    }
</style>

{% if request.user.is_authenticated %}
    <h5 style="text-align: end;"><a href="{% url 'chat_app:logoutUser' %}">Logout</a></h5>
    {% else  %}
    <h5 style="text-align: end;"><a href="{% url 'chat_app:login_register' %}">Login</a></h5>
    {% endif %}

<div class="parent">
    <div class="child1">
        <form action="" method="get">
            <input type="text" name="search" id="searchBox"><input type="submit" value="search">
            </form>
<h3><a href="{% url 'chat_app:home' %}">All</a></h3>
<hr>
{% for topic in topics %}
<h3><a href="{% url 'chat_app:home' %}?search={{topic.name}}">{{topic.name}}</a></h3>
<hr>
{% endfor %}
<br>
<a href="{% url 'chat_app:createRoom' %}">Create Room</a>
</div>
<div class="child2">
{% for room in rooms %}
<h1><a href="{% url 'chat_app:room' room.id %}">{{room.name}}</a></h1>
{% if request.user == room.host %}

<a href="{% url 'chat_app:updateRoom' room.id %}">Edit Room</a>
<a href="{% url 'chat_app:deleteRoom' room.id %}">Delete Room</a>
{% endif %}
<hr>
{% endfor %}
</div>
</div>

{% endblock %}

baatcheet/chat_app/templates/chat_app/login_register.html
{% extends 'chat_app/base.html' %}

{% block content %}
{% csrf_token %}
{% for message in messages %}
<h5 style="color: red;">{{message}}</h5>
{% endfor %}
{% if switch == 'login' %}
<h5 style="text-align: end;"><a href="{% url 'chat_app:registerUser' %}">Register</a></h5>
<form action="" method="post">
    {% csrf_token %}
<input type="text" name="username" id="" placeholder="username">
<input type="password" name="password" id="" placeholder="password">
<input type="submit" value="Login">
</form>
{% else %}
<h5 style="text-align: end;"><a href="{% url 'chat_app:login_register' %}">Login</a></h5>
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register">
    </form>
    {% endif %}
{% endblock %}

baatcheet/chat_app/templates/chat_app/room.html
{% extends 'chat_app/base.html' %}
{% block content %}
<style>
    .parent{
        display: grid;
        grid-template-columns: 3fr 1fr;
    }
</style>
<div class="parent">
    <div class="child1">
        <h1>{{rooms.name}}</h1>
<h5>{{rooms.host}}</h5>
<h5>Created : {{rooms.created}}</h5>
<h5>Updated : {{rooms.updated}}</h5><h5>{{rooms.host}}</h5>
<h5>{{rooms.discription}}</h5>
<h4>{{rooms.topic}}</h4>


<br>
<br>
<br>
<hr>
<h2>Conversations</h2>
<hr>
{% for message in roomMessages %}

<hr>
<small>@{{message.user}}  {{message.created|timesince}}</small>
<h4>{{message.body}}</h4>
{% if request.user == message.user %}
<h6><a href="{% url 'chat_app:deleteMessage' message.id %}">Delete</a> <a href="{% url 'chat_app:editMessage' message.id %}">Edit</a></h6>
{% endif %}
<hr>

{% endfor %}
{% if request.user.is_authenticated %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="addComment" id="" placeholder="Add comments">
    </form>
</div>
{%  endif %}
    </div>
    <div class="child2">
        <hr>
        <h3>Participants</h3>
        {% for participant in participants %}
        <h5>@{{participant}}</h5>
        {% endfor %}
        <hr>
    </div>
</div>
{% endblock %}

baatcheet/chat_app/templates/chat_app/updateRoom.html
{% extends 'chat_app/base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Do you want to update {{rooms.name}}??</p>
        <br>
        <br>
        {{form}}
        <a href="{% url 'chat_app:home' %}">Go back</a>
       <input type="submit" value="Confirm">
    </form>
    {% endblock %}